{
    "language": "python",
    "python": 3.6,
    "install": [
        "pip install pipenv",
        "pipenv install -d --system",
        "pipenv run setup.py"
    ],
    "script": [
        "pipenv run coverage run --source=bot -m unittest discover"
    ],
    "after_success": [
        "pipenv run coverage report",
        "pipenv run codecov"
    ],
    "group": "stable",
    "dist": "trusty",
    "os": "linux"
}
